version: "3.4"

networks:
  aroundhome-network:
    driver: bridge
services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    networks:
      - aroundhome-network
  mock-data:
    image: aroundhome
    build:
      context: .
    depends_on:
      - postgres
    command: /root/aroundhome mock_data
    restart: on-failure
    networks:
      - aroundhome-network
  server:
    image: aroundhome
    build:
      context: .
    command: /root/aroundhome serve_api
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mock-data
    restart: on-failure
    networks:
      - aroundhome-network
