definitions:
  dbutils.PartnerListItem:
    properties:
      distance:
        type: number
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      materials:
        items:
          type: string
        type: array
      name:
        type: string
      radius_in_meters:
        type: integer
      rating:
        type: number
    type: object
  forms.BasicResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
  github.com_taalhach_aroundhome-challennge_internal_server_apihandlers.partnerDetailsResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      partner:
        $ref: '#/definitions/dbutils.PartnerListItem'
      success:
        type: boolean
    type: object
  github.com_taalhach_aroundhome-challennge_internal_server_apihandlers.partnersListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/dbutils.PartnerListItem'
        type: array
      page:
        type: integer
      pages:
        type: integer
      total:
        type: integer
    type: object
  internal_server_apihandlers.partnerDetailsResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      partner:
        $ref: '#/definitions/dbutils.PartnerListItem'
      success:
        type: boolean
    type: object
  internal_server_apihandlers.partnersListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/dbutils.PartnerListItem'
        type: array
      page:
        type: integer
      pages:
        type: integer
      total:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: talhach891@gmail.com
    name: Muhammad Talha
  description: aroundhome's code aroundhome API specs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: aroundhome-challennge API docs
  version: "0.1"
paths:
  /partners:
    get:
      description: This API can be used to retrieve best possible matched partners
        w.r.t distance and rating,
      parameters:
      - description: Floor material
        enum:
        - wood
        - carpet
        - tiles
        in: query
        name: material
        type: string
      - description: 'Latitude(example: 53.544422)'
        in: query
        name: latitude
        type: number
      - description: 'Longitude(example: 10.0011)'
        in: query
        name: longitude
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_taalhach_aroundhome-challennge_internal_server_apihandlers.partnersListResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Get best possible matched partners
  /partners/{id}:
    get:
      description: This API returns partner details.
      parameters:
      - description: Partner Id(example 272)
        in: path
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server_apihandlers.partnerDetailsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Get partner's details
swagger: "2.0"
