definitions:
  apihandlers.pageDataCreateForm:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  apihandlers.pageDataResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      page:
        $ref: '#/definitions/models.PageData'
      success:
        type: boolean
    type: object
  apihandlers.pageDataUpdateForm:
    properties:
      clicks:
        type: integer
      url:
        type: string
      views:
        type: integer
    required:
    - clicks
    - url
    - views
    type: object
  forms.BasicResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
  models.PageData:
    properties:
      clicks:
        type: integer
      created_at:
        type: integer
      id:
        type: integer
      last_updated_at:
        type: integer
      url:
        type: string
      views:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: talhach891@gmail.com
    name: Muhammad Talha
  description: bsdex's code aroundhome API specs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: aroundhome-challennge API docs
  version: "0.1"
paths:
  /page_data:
    get:
      description: |-
        This API can be used to retrieve page data list,
        which is filterable and provides capabilities on basis of all fields.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihandlers.pageDataResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Get page data list
    post:
      consumes:
      - application/json
      description: An API to create page data. If page url already exist this request
        will fail
      parameters:
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/apihandlers.pageDataCreateForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihandlers.pageDataResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Create Page data
    put:
      consumes:
      - application/json
      description: This API is used to update page data. Only clicks and views are
        updated with this Request.
      parameters:
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/apihandlers.pageDataUpdateForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihandlers.pageDataResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Update Page data
  /page_data/{url}:
    get:
      description: This API returns page data details.
      parameters:
      - description: URL
        in: path
        name: url
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihandlers.pageDataResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Get page data's details
  /page_data/{url}/increment:
    patch:
      description: This API is used to increment page views and clicks.
      parameters:
      - description: URL
        in: path
        name: url
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihandlers.pageDataResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/forms.BasicResponse'
      summary: Increments clicks and views
swagger: "2.0"
